default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 51227729
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: my_budget_app_development

test:
  <<: *default
  database: my_budget_app_test


production:
  <<: *default
  database: my_budget_app_production
  username: my_budget_app
  password: <%= ENV["MY_BUDGET_APP_DATABASE_PASSWORD"] %>
